# Generated by Django 4.1.5 on 2023-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companyregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('India', 'India'), ('UAE', 'UAE')], max_length=50)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Dubai', 'Dubai')], max_length=50)),
                ('district', models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Thiruvanathapuram', 'Thiruvanathapuram'), ('Wayanad', 'Wayanad')], max_length=50)),
                ('zipcode', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
