# Generated by Django 4.1.5 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_app', '0005_addservicesmodel_delete_servicesaddmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookservicemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('companyname', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
