# Generated by Django 4.1.5 on 2023-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_app', '0006_bookservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservicesmodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookservicemodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='companyregmodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userregmodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
