# Generated by Django 4.1.5 on 2023-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_app', '0009_addprojectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregmodel',
            name='district',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Al-Karama', 'Al-Karama'), ('Bur Dubai', 'Bur Dubai'), ('Deira', 'Deira'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Thiruvanathapuram', 'Thiruvanathapuram'), ('Wayanad', 'Wayanad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userregmodel',
            name='district',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Al-Karama', 'Al-Karama'), ('Bur Dubai', 'Bur Dubai'), ('Deira', 'Deira'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Thiruvanathapuram', 'Thiruvanathapuram'), ('Wayanad', 'Wayanad')], max_length=50),
        ),
    ]
